[versions]
gradlePlugin-kotlin = "2.3.0"
gradlePlugin-shadow = "9.3.0"
gradlePlugin-semver = "0.9.0"
gradlePlugin-dokka = "2.1.0"

picocli = "4.7.7"
asm = "9.8"
javadiffutils = "4.15"
bytebuddyagent = "1.17.7"
tikka = "3.2.2"

junit5 = "5.13.4"
junit-platform = "1.13.4"

[libraries]
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
javadiffutils = { module = "io.github.java-diff-utils:java-diff-utils", version.ref = "javadiffutils" }
bytebuddy-agent = { module = "net.bytebuddy:byte-buddy-agent", version.ref = "bytebuddyagent" }
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddyagent" }
tika = { module = "org.apache.tika:tika-parser-text-module", version.ref = "tikka" }

# junit jupiter libs
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

assertj-core = { module = "org.assertj:assertj-core", version = "3.27.4" }

gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "gradlePlugin-kotlin" }
gradlePlugin-shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "gradlePlugin-shadow" }
gradlePlugin-semver = { module = "com.javiersc.semver:semver-gradle-plugin", version.ref = "gradlePlugin-semver" }
gradlePlugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "gradlePlugin-dokka" }

[bundles]
asm = ["asm", "asm-util"]

